Add files via upload
smart-edge-open/edgeapps pull request #93
Opened 2022-06-13 03:14 UTC by girivelli

Kfx labs  smart community platform -applications

2022-06-28 07:16 UTC, abjyoti requested changes
Copyright and License Headers are missing.

2022-06-28 07:16 UTC, abjyoti commented on applications/kfxchart/Chart.yaml
> +apiVersion: v2
Copyright and License headers are missing in many files.

2022-07-11 11:45 UTC, girivelli commented
Hi,
I have added the header files and licence for Kfxchart  repository, Please
review and approve
Best Regards,
--Giri.V

On Tue, 28 Jun 2022 at 12:46, ANAND B JYOTI ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Copyright and License Headers are missing.
> ------------------------------
>
> In applications/kfxchart/Chart.yaml
> <https://github.com/smart-edge-open/edgeapps/pull/93#discussion_r908121411>
> :
>
> > @@ -0,0 +1,24 @@
> +apiVersion: v2
>
> Copyright and License headers are missing in many files.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/smart-edge-open/edgeapps/pull/93#pullrequestreview-1021227372>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQEAVAZAFNI4OGMDW7GFAVTVRKRFLANCNFSM5YSYNXIA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-19 04:41 UTC, subhojyoti-intel commented
Kindly commit the latest changes made by you.

2022-08-19 06:36 UTC, girivelli commented
Sure i will get it done by this weekend.
Giri

On Fri, 19 Aug, 2022, 10:11 Subhojyoti Saha, ***@***.***>
wrote:

> Kindly commit the latest changes made by you.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/smart-edge-open/edgeapps/pull/93#issuecomment-1220243281>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQEAVA5PTTFJSHFTNMW7ASLVZ4F7TANCNFSM5YSYNXIA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-22 07:09 UTC, girivelli commented
Pull request to merge initiated . Please  help me to merge .
attached the screenshot

On Tue, 28 Jun 2022 at 12:46, ANAND B JYOTI ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Copyright and License Headers are missing.
> ------------------------------
>
> In applications/kfxchart/Chart.yaml
> <https://github.com/smart-edge-open/edgeapps/pull/93#discussion_r908121411>
> :
>
> > @@ -0,0 +1,24 @@
> +apiVersion: v2
>
> Copyright and License headers are missing in many files.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/smart-edge-open/edgeapps/pull/93#pullrequestreview-1021227372>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQEAVAZAFNI4OGMDW7GFAVTVRKRFLANCNFSM5YSYNXIA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-08-25 03:22 UTC, abjyoti commented on applications/kfxchart/helmchart/templates/deployment.yaml
> +SPDX-License-Identifier: Apache-2.0
"#" is missing at the beginning of the line

2022-08-25 03:28 UTC, abjyoti requested changes
Please resolve the comments.

2022-08-25 03:28 UTC, abjyoti commented on applications/kfxchart/helmchart/templates/hpa.yaml
> +SPDX-License-Identifier: Apache-2.0
"#" is missing at the beginning of the line

2022-08-25 03:28 UTC, abjyoti commented on applications/kfxchart/helmchart/templates/ingress.yaml
> +SPDX-License-Identifier: Apache-2.0
"#" is missing at the beginning of the line

2022-08-25 03:28 UTC, abjyoti commented on applications/kfxchart/helmchart/templates/service.yaml
> +SPDX-License-Identifier: Apache-2.0
"#" is missing at the beginning of the line

2022-08-25 03:28 UTC, abjyoti commented on applications/kfxchart/helmchart/templates/tests/test-connection.yaml
> +SPDX-License-Identifier: Apache-2.0
"#" is missing at the beginning of the line

2022-08-25 03:28 UTC, abjyoti commented on applications/kfxchart/helmchart/values.yaml
> +SPDX-License-Identifier: Apache-2.0
"#" is missing at the beginning of the line

2022-08-25 03:28 UTC, abjyoti commented on applications/kfxchart/readme.md
> +Copyright (c) 2022 Kfxlabs and circuits private Limited
"#" is missing at the beginning of the line

2022-08-25 03:28 UTC, abjyoti commented on applications/kfxchart/readme.md
> +SPDX-License-Identifier: Apache-2.0
"#" is missing at the beginning of the line

2022-09-19 07:55 UTC, abjyoti approved these changes
LGTM... My comments are resolved.

2022-09-19 07:55 UTC, merged